### ISSUE TITLE
log.* is used throughout the project without requiring it

### ISSUE THREAD

**Issue by deAngelisAlex** [mandrag0ra/opennic-desktop#1]
Hello,

I've reviewed the code for your project and noticed the use of log.* functions ([win32.js#90](https://github.com/mandrag0ra/opennic-desktop/blob/master/lib/win32.js#L90), [darwin.js#99](https://github.com/mandrag0ra/opennic-desktop/blob/master/lib/darwin.js#L99)) from the electron-log package but they're not required in either of those files.

Can you fix this little bug or should I PR?

(Also, when there's an error, the program should make an alert or notify the user of the error, instead of ignoring it and logging it [main.js#93](https://github.com/mandrag0ra/opennic-desktop/blob/master/main.js#L93))

deAngelisAlex

**Comment by mandrag0ra** [comment]
Hi,

Sure ! Thanks for pointing this out. The required modules has been had.

For the notification, the main window would actually be different ([main.js#41](https://github.com/mandrag0ra/opennic-desktop/blob/00d2b58762d9a4f5633d8582262aae1465b8b442/main.js#L41)) if the ping command failed. 
But you're right, I might find a better way to do this.

**Comment by mandrag0ra** [comment]
Hi @deAngelisAlex,

I might have found a proper way to handle the errors you've pointed out.

Thanks again for your review.
